client/src/components/ChooseSeats.jsx
client/src/components/TicketCounter.jsx
client/src/main.jsx
client/src/pages/BookMovie.jsx

added new files and a new route

---

Psuedo/Psude.js

wrote some psuedoCode to help us with the backend endpoints

---

server/src/controller/adminController.js
server/src/util/jwtUtil.js
server/src/util/seatNumberUtil.js

changed the calculation of theater seats

---

client/src/components/BookMovieHero.jsx
client/src/components/BookingTicketsForm.jsx
client/src/components/bookMovie/BookingPartTwo.jsx
client/src/components/bookMovie/ConfirmBooking.jsx
client/src/components/bookMovie/TicketCounter.jsx
client/src/pages/Booking.jsx
client/src/service/fetchService.js

changed styling for the booking/booking confirmation pages

---

server/src/controller/adminController.js
server/src/util/newDateFormate.js

Veckodag i screenings i önskat format "söndag 12 december"

---

client/src/components/adminPage/AddScreeningForm.jsx
client/src/pages/Admin/AdminAddScreenings.jsx

Adminaddscreening

---

client/src/components/bookMovie/ChooseSeats.jsx
client/src/components/bookMovie/TicketCounter.jsx
client/src/pages/booking/BookMovie.jsx

Seat rewamp

---

server/src/controller/userController.js

Sorterar nu på närmaste datum och tidigast tid.

Sorting date time

---

server/src/controller/adminController.js

Denna ändring fanns med i original branchen som jag var tvungen att välja bort pga av säkerhetsrisker keys. Den skulle ha följt med förra pull requesten

ny property uxDate får värdet av newDateFormate(date)

---

client/src/components/Header.jsx

clicking profile button or name when logged in now takes you to mypages

---

client/src/components/ScreeningCard.jsx
client/src/pages/MovieDetails.jsx

Fixerrorscreeningcard

---

client/src/components/bookMovie/ConfirmBooking.jsx
client/src/pages/Tickets.jsx
client/src/pages/booking/BookingTickets.jsx
server/src/util/newDateFormate.js

Cssconfirmaiton

---

client/src/components/bookMovie/TicketCounter.jsx

Seperate seats

---

client/src/pages/Home.jsx
client/src/pages/MovieDetails.jsx

Lazyloaderfix

---

client/src/components/bookMovie/ChooseSeats.jsx
client/src/components/bookMovie/SeperateSeatsToggle.jsx
client/src/components/bookMovie/TicketCounter.jsx
client/src/index.css
client/src/pages/booking/BookMovie.jsx

Front end seprarate seats

---

client/src/components/userPage/CancelBooking.jsx
client/src/pages/MyPages.jsx
server/src/controller/sseController.js

My pages+cancel booking

---

server/src/controller/userController.js

Onlyscreeningsfromtoday

---

client/src/components/adminPage/AddMovieForm.jsx
client/src/components/adminPage/AddScreeningForm.jsx
client/src/main.jsx
client/src/pages/Admin/Admin.jsx
client/src/pages/Admin/AdminAddMovies.jsx
client/src/pages/Admin/AdminAddScreenings.jsx
client/src/pages/Admin/AdminBookings.jsx
client/src/pages/Admin/AdminUsers.jsx

added nested admin routes

---

client/src/App.jsx
client/src/assets/carouselData.js
client/src/components/Header.jsx
client/src/components/homePage/multi-carousel-upComing.jsx
client/src/main.jsx
client/src/pages/Movies.jsx
client/src/styles.js

Nav-fix, wrapping fungerar nu på nav och global. Rensning av padding, margins + globala styles för detta för samtliga kompontenter och sidor nästa steg.
Senaste dev nedladdad.

Css cleaning2.0

---

client/src/components/bookMovie/BookingTicketsForm.jsx
client/src/components/bookMovie/ConfirmBooking.jsx
client/src/styles.js

Admin bokningar

---

client/src/service/fetchService.js

Perform request

---

client/src/components/Header.jsx

The return of the border
Mergad med dev

Nav border

---

client/src/components/Header.jsx
client/src/index.css

fixed carousel arrows to look like our mockup

---

client/src/pages/MovieDetails.jsx

fixin age information on one more place. looks good now

---

client/src/components/bookMovie/BookingTicketsForm.jsx
client/src/components/bookMovie/ConfirmBooking.jsx
client/src/components/moviesPage/MovieCard.jsx
client/src/components/moviesPage/MovieTrailer.jsx
client/src/pages/booking/BookingTickets.jsx

Fixingconsoleerrors

---

client/src/pages/MovieDetails.jsx

Detaljsida=mockup
